### ISSUE TITLE
About install the repo

### ISSUE THREAD

**Issue by Roywangj** [idanachi/DefRec_and_PCM#27]
Hi, 
When i dont install the repo, i will meet problems in https://github.com/IdanAchituve/DefRec_and_PCM/issues/7. But it works when i install the repo. 
However, i check the setup.py, it doesn't add utils into environment, thats confused to me.

Would you please help me understand it?

**Comment by IdanAchituve** [comment]
Hi,
Can you please clarify your question? you are asking how come utils.py is recognized in the compilation process even though it is not installed directly?

**Comment by Roywangj** [comment]
Hi,

Yes. I think there is no any cuda extensions, so there is no need to compile files, just adjust relative paths of the file will work.

**Comment by IdanAchituve** [comment]
As far as I know, Python does make some sort of compilation to byte code, but it is not relevant. Anyway, my understanding is that the installation of the repository adds the path of the project to sys.path.

**Comment by Roywangj** [comment]
Hi, thanks for your reply, it helps me.
