### ISSUE TITLE
Different results on Table 1 & 2

### ISSUE THREAD

**Issue by Marsrocky** [idanachi/DefRec_and_PCM#3]
What is the difference of Table 1 and 2 in your paper? The results seem different but I cannot find the different experimental settings or descriptions. Thanks.

**Comment by idanachi** [comment]
Hi,
Table 1 - baselines methods are without PCM. Taken as is.
Table 2 - we incorporated PCM to baseline methods and compared with our
method (with PCM).

**Comment by Marsrocky** [comment]
Thanks four your explanations. The comparison can further elaborate the effectiveness of PCM w.r.t. a wider field (DA or SSL methods).
